import type { ImageAsset } from "@/content/image-asset";

export const pageImages = {
  aboutHero: {
    id: "about-hero",
    src: "/brand/pages/about/about-hero.webp",
    alt: "A staffing partner and operations leader walking through an active facility.",
    label: "Partnership on the floor",
    aspectRatio: "16:10",
    width: 2400,
    height: 1500,
    focalPoint: "68% 50%",
  },
  companyJourney: {
    id: "company-journey",
    src: "/brand/pages/about/company-journey.webp",
    alt: "A staffing professional observing the flow of an active industrial operation.",
    label: "Operational continuity",
    aspectRatio: "3:2",
    width: 2100,
    height: 1400,
    focalPoint: "center",
  },
  missionInPractice: {
    id: "mission-in-practice",
    src: "/brand/pages/about/mission-in-practice.webp",
    alt: "A supervisor orienting a worker near an active production floor.",
    label: "Mission in practice",
    aspectRatio: "4:5",
    width: 1600,
    height: 2000,
    focalPoint: "center",
  },
  valuesOnTheFloor: {
    id: "values-on-the-floor",
    src: "/brand/pages/about/values-on-the-floor.webp",
    alt: "A production team completing a careful pre-shift equipment check.",
    label: "Values on the floor",
    aspectRatio: "4:3",
    width: 1800,
    height: 1350,
    focalPoint: "center",
  },
  teamCulture: {
    id: "team-culture",
    src: "/brand/pages/about/team-culture.webp",
    alt: "Staffing and operations professionals reviewing the day together.",
    label: "Team culture",
    aspectRatio: "3:2",
    width: 2100,
    height: 1400,
    focalPoint: "35% 50%",
  },
  employersHero: {
    id: "employers-hero",
    src: "/brand/pages/employers/employers-hero.webp",
    alt: "An operations manager and staffing strategist reviewing workforce needs.",
    label: "Workforce planning conversation",
    aspectRatio: "16:10",
    width: 2400,
    height: 1500,
    focalPoint: "68% 50%",
  },
  workforceOverview: {
    id: "workforce-overview",
    src: "/brand/pages/employers/workforce-overview.webp",
    alt: "An operations leader reviewing shift coverage with a staffing partner.",
    label: "Workforce overview",
    aspectRatio: "4:5",
    width: 1600,
    height: 2000,
    focalPoint: "center",
  },
  temporaryStaffing: {
    id: "temporary-staffing",
    src: "/brand/pages/employers/temporary-staffing.webp",
    alt: "A worker receiving a shift briefing from an operations supervisor.",
    label: "Temporary staffing",
    aspectRatio: "4:3",
    width: 1800,
    height: 1350,
    focalPoint: "65% 50%",
  },
  tempToHire: {
    id: "temp-to-hire",
    src: "/brand/pages/employers/temp-to-hire.webp",
    alt: "A supervisor reviewing completed work with a production employee.",
    label: "Temp-to-hire",
    aspectRatio: "4:3",
    width: 1800,
    height: 1350,
    focalPoint: "center",
  },
  directHire: {
    id: "direct-hire",
    src: "/brand/pages/employers/direct-hire.webp",
    alt: "An experienced operations professional touring a facility with a plant leader.",
    label: "Direct hire",
    aspectRatio: "4:3",
    width: 1800,
    height: 1350,
    focalPoint: "35% 50%",
  },
  seasonalStaffing: {
    id: "seasonal-staffing",
    src: "/brand/pages/employers/seasonal-staffing.webp",
    alt: "A fully staffed packaging operation handling increased seasonal volume.",
    label: "Seasonal staffing",
    aspectRatio: "4:3",
    width: 1800,
    height: 1350,
    focalPoint: "center",
  },
  highVolumeStaffing: {
    id: "high-volume-staffing",
    src: "/brand/pages/employers/high-volume-staffing.webp",
    alt: "Multiple staffed work zones operating together under supervisor oversight.",
    label: "High-volume staffing",
    aspectRatio: "4:3",
    width: 1800,
    height: 1350,
    focalPoint: "center",
  },
  workforcePlanning: {
    id: "workforce-planning",
    src: "/brand/pages/employers/workforce-planning.webp",
    alt: "A staffing strategist mapping future shift requirements with an operations leader.",
    label: "Workforce planning",
    aspectRatio: "4:3",
    width: 1800,
    height: 1350,
    focalPoint: "65% 50%",
  },
  processHandoff: {
    id: "process-handoff",
    src: "/brand/pages/employers/process-handoff.webp",
    alt: "A continuous workplace scene connecting planning, recruiting, and placement.",
    label: "Process handoff",
    aspectRatio: "16:7",
    width: 2400,
    height: 1050,
    focalPoint: "center",
  },
  industriesHero: {
    id: "industries-hero",
    src: "/brand/pages/industries/industries-hero.webp",
    alt: "Workers moving through a facility that combines production and distribution.",
    label: "Industries we serve",
    aspectRatio: "16:10",
    width: 2400,
    height: 1500,
    focalPoint: "center",
  },
  manufacturingTeam: {
    id: "manufacturing-team",
    src: "/brand/pages/industries/manufacturing-team.webp",
    alt: "Manufacturing workers completing a production-line quality check.",
    label: "Manufacturing",
    aspectRatio: "4:3",
    width: 1800,
    height: 1350,
    focalPoint: "65% 50%",
  },
  distributionFlow: {
    id: "distribution-flow",
    src: "/brand/pages/industries/distribution-flow.webp",
    alt: "Distribution workers scanning and preparing inventory in an active aisle.",
    label: "Warehouse and distribution",
    aspectRatio: "4:3",
    width: 1800,
    height: 1350,
    focalPoint: "center",
  },
  logisticsCoordination: {
    id: "logistics-coordination",
    src: "/brand/pages/industries/logistics-coordination.webp",
    alt: "Logistics professionals coordinating outbound freight at a loading dock.",
    label: "Logistics",
    aspectRatio: "4:3",
    width: 1800,
    height: 1350,
    focalPoint: "35% 50%",
  },
  administrativeOperations: {
    id: "administrative-operations",
    src: "/brand/pages/industries/administrative-operations.webp",
    alt: "An administrative professional coordinating schedules beside an operations floor.",
    label: "Administrative support",
    aspectRatio: "4:3",
    width: 1800,
    height: 1350,
    focalPoint: "65% 50%",
  },
  customerSupportTeam: {
    id: "customer-support-team",
    src: "/brand/pages/industries/customer-support-team.webp",
    alt: "Customer support professionals handling calls in an operations office.",
    label: "Customer service",
    aspectRatio: "4:3",
    width: 1800,
    height: 1350,
    focalPoint: "center",
  },
  lightIndustrialProcess: {
    id: "light-industrial-process",
    src: "/brand/pages/industries/light-industrial-process.webp",
    alt: "Light industrial workers assembling and inspecting products at an orderly line.",
    label: "Light industrial",
    aspectRatio: "4:3",
    width: 1800,
    height: 1350,
    focalPoint: "center",
  },
  jobSeekersHero: {
    id: "job-seekers-hero",
    src: "/brand/pages/job-seekers/job-seekers-hero.webp",
    alt: "A supervisor welcoming a worker into an active workplace.",
    label: "Career opportunity",
    aspectRatio: "16:10",
    width: 2400,
    height: 1500,
    focalPoint: "35% 50%",
  },
  careerCenter: {
    id: "career-center",
    src: "/brand/pages/job-seekers/career-center.webp",
    alt: "A recruiter reviewing career options with a job seeker.",
    label: "Career Center",
    aspectRatio: "3:2",
    width: 2100,
    height: 1400,
    focalPoint: "center",
  },
  applicationProcess: {
    id: "application-process",
    src: "/brand/pages/job-seekers/application-process.webp",
    alt: "A continuous scene connecting recruiter support to a workplace introduction.",
    label: "Application process",
    aspectRatio: "16:7",
    width: 2400,
    height: 1050,
    focalPoint: "center",
  },
  resumeSupport: {
    id: "resume-support",
    src: "/brand/pages/job-seekers/resume-support.webp",
    alt: "A job seeker preparing application materials with recruiter support.",
    label: "Résumé support",
    aspectRatio: "4:5",
    width: 1600,
    height: 2000,
    focalPoint: "center",
  },
  recruiterSupport: {
    id: "recruiter-support",
    src: "/brand/pages/job-seekers/recruiter-support.webp",
    alt: "A recruiter checking in with a worker near the workplace.",
    label: "Recruiter support",
    aspectRatio: "3:2",
    width: 2100,
    height: 1400,
    focalPoint: "center",
  },
  jobsHero: {
    id: "jobs-hero",
    src: "/brand/pages/jobs/jobs-hero.webp",
    alt: "Professionals working across production, distribution, and operations support.",
    label: "Open opportunities",
    aspectRatio: "16:10",
    width: 2400,
    height: 1500,
    focalPoint: "68% 50%",
  },
  opportunityContext: {
    id: "opportunity-context",
    src: "/brand/pages/jobs/opportunity-context.webp",
    alt: "A skilled worker entering an active facility at the start of a shift.",
    label: "Opportunity context",
    aspectRatio: "4:5",
    width: 1600,
    height: 2000,
    focalPoint: "center",
  },
  workplaceOpportunities: {
    id: "workplace-opportunities",
    src: "/brand/pages/jobs/workplace-opportunities.webp",
    alt: "Professionals working in several roles across one active facility.",
    label: "Workplace opportunities",
    aspectRatio: "16:9",
    width: 2400,
    height: 1350,
    focalPoint: "center",
  },
  contactHero: {
    id: "contact-hero",
    src: "/brand/pages/contact/contact-hero.webp",
    alt: "A staffing professional listening to an operations manager near the facility floor.",
    label: "Start a conversation",
    aspectRatio: "16:10",
    width: 2400,
    height: 1500,
    focalPoint: "center",
  },
  employerConversation: {
    id: "employer-conversation",
    src: "/brand/pages/contact/employer-conversation.webp",
    alt: "An employer discussing staffing requirements with a workforce specialist.",
    label: "Request talent",
    aspectRatio: "4:5",
    width: 1600,
    height: 2000,
    focalPoint: "center",
  },
  resourcesHero: {
    id: "resources-hero",
    src: "/brand/pages/resources/resources-hero.webp",
    alt: "Workforce and career materials being reviewed at a practical resource desk.",
    label: "Resource Center",
    aspectRatio: "16:10",
    width: 2400,
    height: 1500,
    focalPoint: "68% 50%",
  },
  companyNews: {
    id: "company-news",
    src: "/brand/pages/resources/company-news.webp",
    alt: "Staffing and operations professionals walking through an active facility.",
    label: "Company news",
    aspectRatio: "3:2",
    width: 1800,
    height: 1200,
    focalPoint: "35% 50%",
  },
} satisfies Record<string, ImageAsset>;

function reuse(
  source: ImageAsset,
  overrides: Pick<ImageAsset, "id" | "alt" | "label">,
): ImageAsset {
  return { ...source, ...overrides };
}

/**
 * Dedicated files for these seven slots were never generated. Each reuses an
 * existing photograph with a matching scene and crop until originals arrive.
 * Do not place a reused source twice on the same page.
 */
export const reusedPageImages = {
  candidateConversation: reuse(pageImages.resumeSupport, {
    id: "candidate-conversation",
    alt: "A recruiter answering a job seeker’s question.",
    label: "Candidate conversation",
  }),
  serviceAreaOperations: reuse(pageImages.companyJourney, {
    id: "service-area-operations",
    alt: "Employees arriving at a working industrial facility in the tri-state region.",
    label: "Service area operations",
  }),
  workforceInsights: reuse(pageImages.workforcePlanning, {
    id: "workforce-insights",
    alt: "Operations leaders comparing workforce notes and shift patterns.",
    label: "Workforce insights",
  }),
  industryReports: reuse(pageImages.manufacturingTeam, {
    id: "industry-reports",
    alt: "Operations professionals reviewing a production summary beside machinery.",
    label: "Industry reports",
  }),
  employerGuides: reuse(pageImages.workforceOverview, {
    id: "employer-guides",
    alt: "A staffing specialist reviewing hiring requirements with an employer.",
    label: "Employer resources",
  }),
  careerAdvice: reuse(pageImages.careerCenter, {
    id: "career-advice",
    alt: "A job seeker practicing interview preparation with a recruiter.",
    label: "Career advice",
  }),
  resourceDesk: reuse(pageImages.recruiterSupport, {
    id: "resource-desk",
    alt: "A recruiter organizing workforce and career resources at a worktable.",
    label: "Resource desk",
  }),
} satisfies Record<string, ImageAsset>;

export type PageImageId = keyof typeof pageImages;
